default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: yetanothershop_development

test:
  <<: *default
  database: yetanothershop_test

production:
  <<: *default
  database: yetanothershop_production
  username: yetanothershop
  host: localhost
  password: <%= ENV['YETANOTHERSHOP_DATABASE_PASSWORD'] %>
